# Generated by Django 5.2.8 on 2025-11-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_register",
            name="first_name",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user_register",
            name="last_name",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
