# Generated by Django 5.2.8 on 2025-11-17 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_user_register_first_name_user_register_last_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user_register",
            name="confirm_password",
        ),
    ]
