# Generated by Django 5.2.8 on 2025-11-21 07:03

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_course"),
    ]

    operations = [
        migrations.CreateModel(
            name="lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", ckeditor_uploader.fields.RichTextUploadingField()),
                ("video_url", models.URLField(blank=True, null=True)),
                (
                    "pdf_material",
                    models.FileField(blank=True, null=True, upload_to="course_pdfs/"),
                ),
                (
                    "Course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.course"
                    ),
                ),
            ],
        ),
    ]
