# Generated by Django 5.2.8 on 2025-11-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_lesson"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="video_url",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
