# Generated by Django 5.2.8 on 2025-11-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_student_reg_alter_course_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="student_reg",
            name="purchased_courses",
            field=models.ManyToManyField(blank=True, null=True, to="myapp.course"),
        ),
    ]
