# Generated by Django 5.2.8 on 2025-12-02 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_lessonprogress_mcqquestion_delete_user_register"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LessonProgress",
        ),
    ]
