# Generated by Django 5.2.8 on 2025-12-02 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0010_delete_lessonprogress"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mcqquestion",
            name="lesson",
        ),
        migrations.AddField(
            model_name="mcqquestion",
            name="course",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mcqs",
                to="myapp.course",
            ),
            preserve_default=False,
        ),
    ]
