# Generated by Django 5.2.8 on 2025-12-08 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_remove_mcqquestion_lesson_mcqquestion_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="courseduration",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
