# Generated by Django 5.2.8 on 2025-12-08 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0012_course_courseduration"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="courseduration",
            new_name="course_duration",
        ),
    ]
