# Generated by Django 5.2.8 on 2025-12-11 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0013_rename_courseduration_course_course_duration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percent", "Percent"), ("flat", "Flat")],
                        max_length=10,
                    ),
                ),
                ("discount_value", models.IntegerField()),
                ("active", models.BooleanField(default=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("min_amount", models.IntegerField(default=0)),
                ("max_uses_per_user", models.IntegerField(blank=True, null=True)),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("all", "All Users"),
                            ("new", "New Users"),
                            ("existing", "Existing Users"),
                        ],
                        default="all",
                        max_length=20,
                    ),
                ),
                (
                    "allowed_courses",
                    models.ManyToManyField(blank=True, to="myapp.course"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CouponUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("used_at", models.DateTimeField(auto_now_add=True)),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.coupon"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
